### ISSUE TITLE
Using @JsonValue on an enum with Lombok

### ISSUE THREAD

**Issue by mjustin** [mjustin/springdoc-openapi#1]
Responding to this [comment](https://github.com/springdoc/springdoc-openapi/issues/1244#event-5906679936) by @harvanchik which was deleted from springdoc/springdoc-openapi/issues/1244 by the project owner:

> Is it possible to combine this with lombok? This did not work.
> 
> ```java
> @Getter @JsonValue
> public enum DevelopmentPhase {
> 
>     UNKNOWN(0, "Unknown"),
>     BETA(1, "Beta"),
>     GAMMA(2, "Gamma"),
>     PRODUCTION(3, "Production"),
>     MAINTENANCE(4, "Maintenance");
> 
>     private final int value;
>     private final String name;
> 
>     DevelopmentPhase(final int value, @NotNull final String name) {
>         this.value = value;
>         this.name = name;
>     }
> ```
> 
> And this did not work either.
> 
> ```java
> @Getter
> public enum DevelopmentPhase {
> 
>     UNKNOWN(0, "Unknown"),
>     BETA(1, "Beta"),
>     GAMMA(2, "Gamma"),
>     PRODUCTION(3, "Production"),
>     MAINTENANCE(4, "Maintenance");
> 
>     @JsonValue private final int value;
>     @JsonValue private final String name;
> 
>     DevelopmentPhase(final int value, @NotNull final String name) {
>         this.value = value;
>         this.name = name;
>     }
> ```

Yes, it is possible; you just need to [tell Lombok](https://projectlombok.org/features/GetterSetter) to add the annotation to the getter method, using `@Getter(onMethod_ = @JsonValue)` on the field:

```java
@Getter
public enum DevelopmentPhase {

    UNKNOWN(0, "Unknown"),
    BETA(1, "Beta"),
    GAMMA(2, "Gamma"),
    PRODUCTION(3, "Production"),
    MAINTENANCE(4, "Maintenance");

    @Getter(onMethod_ = @JsonValue)
    private final int value;

    @Getter(onMethod_ = @JsonValue)
    private final String name;

    DevelopmentPhase(final int value, @NotNull final String name) {
        this.value = value;
        this.name = name;
    }
```

**Comment by harvanchik** [comment]
Thank you very much for responding to my comment even though it was deleted.  I appreciate the help!

**Comment by mjustin** [comment]
Glad to be of assistance. :-)
